### ISSUE TITLE
product.module.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [dizayner/angular-training#2]
CoreModule - это такой модуль, который по договоренности подключается только к AppModule.  Нет необходимости подключать его и в ProductsModule. Все его сервисы будут доступны.

ProductComponent не используется за рамками модуля ProductModule. Нет необходимости его экспортировать.

Пустые секции декоратора @NgModule можно не писать.

**Comment by dizayner** [comment]
Поправил
