### ISSUE TITLE
product.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [dizayner/angular-training#3]
Можно упростить этот компонент, убрав зависимость и реализовав этот компонент как презентационный. Если надо добавить в корзину товар, то пусть он его передает родительскому, а тот уже добавляетв корзину. Получиться, что у ProductListComponent буду зависимости, а у ProductComponent нет. Чем меньше простых действий выполняет компонент и меньше у него зависимостей, тем проще его тестировать.

**Comment by dizayner** [comment]
Я так делал исходя из того, что в последсвтии можно вставить ProductComponent в любое место и не потеряв функционалости "покупки" (напрример, "товар дня", "похожие товары")

**Comment by VZhyrytskiy** [comment]
ОК
